version: '3.4'

services:

  timetracking.front:
    image: ${DOCKER_REGISTRY-}timetracking.front
    container_name: timetracking.front
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"