export const REGISTER = "REGISTER";
export const CONFIRM_EMAIL = "CONFIRM_EMAIL";
export const CREATE_TOKEN = "CREATE_TOKEN";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESEND_VERIFICATION_EMAIL = "RESEND_VERIFICATION_EMAIL";
export const REVOKE_TOKEN = "REVOKE_TOKEN";
