export const FETCH_ISSUE_BY_ID = "FETCH_ISSUE_BY_ID";
export const ASSIGN_ISSUE_TO_USER_BY_ID = "ASSIGN_ISSUE_TO_USER_BY_ID";
export const CHANGE_ISSUE_STATUS = "CHANGE_ISSUE_STATUS";
export const CREATE_ISSUE = "CREATE_ISSUE";
export const GET_ALL_ISSUES_ASYNC = "GET_ALL_ISSUES_ASYNC";
