export const GET_ALL_ACTIVITIES_FOR_USER = "GET_ALL_ACTIVITIES_FOR_USER";
export const CREATE_WORKLOG = "CREATE_WORKLOG";
export const UPDATE_WORKLOG = "UPDATE_WORKLOG";
export const UPDATE_WORKLOG_STATUS = "UPDATE_WORKLOG_STATUS";
export const GET_ALL_WORKLOGS_PAGED = "GET_ALL_WORKLOGS_PAGED";
export const DELETE_WORKLOG = "DELETE_WORKLOG";
export const FETCH_WORKLOG_BY_ID = "FETCH_WORKLOG_BY_ID";
